# style_edition = "2024"

max_width = 111

brace_style = "PreferSameLine"
empty_item_single_line = true
enum_discrim_align_threshold = 45
struct_field_align_threshold = 45

format_code_in_doc_comments = true
format_strings = true


fn_params_layout = "Compressed"
fn_single_line = true


short_array_element_width_threshold = 30
hard_tabs = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true

format_macro_matchers = true
format_macro_bodies = true
attr_fn_like_width = 110
array_width = 110
fn_call_width = 110
chain_width = 110
comment_width = 110
struct_lit_width = 110
struct_variant_width = 110
single_line_if_else_max_width = 110


imports_granularity = "Module"
imports_layout="Horizontal"
match_block_trailing_comma = true
