[unstable]
# codegen-backend = true
# build-std = ["core","alloc", "std", "compiler_builtins"]
# build-std = ["core", "alloc", "std"]
[rust]
[build]
# target = "x86_64-unknown-linux-musl"
# debuginfo-level = 1
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  # "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-fuse-ld=/home/vedran/.cargo/bin/wild",
  # "-C", "target-feature=+avx,+avx2",
# "-Zbuild-std",
 # "-C","target-cpu=native",
 "-C", "force-frame-pointers=yes",
]

