name: Run tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  CARGO_TERM_COLOR: always
jobs:
  TestEvalexpr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evalexpr
    steps:
      - uses: actions/checkout@v5
      - name: Move .cargo/config.toml out of the way
        run: mv ../.cargo/config.toml ../.cargo/config.toml.bak
      - name: Run tests in debug mode
        run: cargo test
      - name: Run tests in release mode
        run: cargo test --release
