name: Run tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  TestEvalexpr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./evalexpr
    steps:
      - uses: actions/checkout@v5
      - name: Run tests in debug mode
        run: cargo test
      - name: Run tests in release mode
        run: cargo test --release
